### ISSUE TITLE
 Pop up menu in a read only calendar throws NPE and self message dialog

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#101]
After set the calendars in read only mode and press right mouse button the calendar widget throws NPE and a unmodifiable message dialog. 
The NPE has to be improve and it should be possible remove ths message dialog (optionally add replace with dialogs form own implementation). See screenshots.
![2020-07-23_10h08_14](https://user-images.githubusercontent.com/68653276/88264914-deb4b180-cccc-11ea-8f0d-28d4523976ec.png)
![2020-07-23_10h08_29](https://user-images.githubusercontent.com/68653276/88264917-df4d4800-cccc-11ea-9fdf-100fbf63ad22.png)
![2020-07-23_10h08_54](https://user-images.githubusercontent.com/68653276/88264919-dfe5de80-cccc-11ea-82da-8550cc3f8808.png)

**Comment by dlemmermann** [comment]
The calendar reference of the context menu callback parameter may now be null. Moved the logic for showing the problem dialog out of the default calendar provider callback into code closer to the UI / view code.
