### ISSUE TITLE
Double clicking on read only calendars creates an entry

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#102]
It should not be possible add/edit or remove entries in the read only calendars.
See New Entry 1 - created after double click on calendar. Calendar is still in read only mode.
![2020-07-23_10h43_53](https://user-images.githubusercontent.com/68653276/88267661-6dc3c880-ccd1-11ea-8757-1b12e1e878a2.png)

**Comment by dlemmermann** [comment]
I have added an isReadOnly() check to the DateControl.createEntryAt() method. The method can now return null if the calendar does not allow editing.
