### ISSUE TITLE
Focus on calendarEntry returns on focus on window.

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#103]
Lets have entry on calendar view. Click on it (just to gain focus on entry) and after that click on background of calendar (just to lost focus on entry). Now switch to other window and go back to calendarFX window. Previously entry that was un-focused now it's focused.

![2020-07-29_14h25_17](https://user-images.githubusercontent.com/68653276/88800149-fa75f700-d1a7-11ea-9585-f92fcaaa1bb3.gif)

**Comment by dlemmermann** [comment]
Fixed. DateControl now has a mouse clicked listener that will run when the user clicks into the white background. That listener then tells the DateControl to request focus.
