### ISSUE TITLE
Layers functionality for CalendarFX?

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#105]
In our project we would like to have the additional layers functionality for CalendarFX, that would be aware of entries placement underneath.

Intention:

We would like to position additional visual elements, which would be placed above or in relation to calendar entries.
A good example would be notes, some relation lines between entries or adding highlighting borders over some set of items.

Layer should be expanded over all DayViews available in ResourceCalendarView. Sometimes we would like to display something outside of space taken by DayView, or somewhere nerby in relation to it (but still in the layers space) - it would be very similar to how it is being done for LinksPane in FlexGanttFX.

We imagine that layers API for CalendarFX should give us ability to:

- define a new layer on top of CalendarFX (with access to JavaFX canvas)
- define z-order of layer in relation to other layers
- register an item views factory for given layer, this factory would provide visual elements visible on the layer
- use observable collection of model items, that would be passed to view factory 
- register layer listener on the main layer (calendar entries) for event when a new calendar view entry is added (when calendar is rendered when scrolled, time scale changes etc.), this listener should provide information about:
    - position of calendar entry (in local coordinates of the defined layer)
    - size of calendar entry
    - reference of the calendar entry view placed underneath
- register layer listener on the main layer render event (views are removed)

Please let us know: what do you think about this concept/functionality? Would you be interested in implementing it? If yes we would also welcome any suggestions for improvements.

Best regards,
PSI Polska - ASM Team

**Comment by dlemmermann** [comment]
CalendarFX consists of many different controls, each one having it’s own skin. So when you say “..define a new layer on top of CalendarFX …” you actually have to say: “…. add the option for working with overlay layers for every control / this list of controls ….”. Knowing your application I assume you are basically thinking of the DayView control, right? So please be more specific and let me know which control you mean.

Regarding the feasibility: I do not know if this can be implemented at all and I definitely can not say if any potential result will be nice (in behaviour and / or appearance). This is a major feature that usually takes me months to develop properly without any guarantee for success. This is not a small item. I have my doubts that PSI would finance such a vague feature implementation.

One more thing: mixing the Scenegraph approach (nodes) with the Canvas approach is very tricky. Synchronizing the rendering between these two concepts is not easy.
