### ISSUE TITLE
Invisible time scale column when technical detail node is open on the left side

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#106]
The requeiment is hide time scale in master detail pane when the technical detail node is visible on the left side.
1. Does it is possible to do this in CalendarFx ?
2. Does it is  possible to remove all column of time scale  not only texts ?
![2020-08-26_09h58_22](https://user-images.githubusercontent.com/68653276/91278006-e9f37500-e783-11ea-9a9b-c441f4e23631.png)

**Comment by dlemmermann** [comment]
I have added a property to ResourceCalendarView called "showTimeScale". You can bind it to something in your app to make the timescale disappear when needed.
