### ISSUE TITLE
Proposal of code donation: "Zoom" strategy for DayEntryViews

### ISSUE THREAD

**Issue by PSI-Polska-ASM** [dlemmermann/CalendarFX#107]
Hi, 
We would like to introduce you our proposal of code donation: "Zoom" strategy for DayEntryViews. "Zoom" here is increasing and decreasing height of hours in CalendarFX - which affects on vertical space of entry.
Right now when we zoom out view, DayEntryView children like title and nodes are stacked when height of entry is too small (except of startTimeLabel which is hidden when size is too small).

Our vision:
We want to implement alternative version of SkinBase<DayEntryView> which can be used instead of default DayEntryViewSkin. 
New mechanism would base on "visibility weight" of elements added to entry (greater weight - longer it stays on screen when height of entry is decreasing).
To achieve our goal we want to split entry vertically into "segments" (Title will be represented as segment as well).
Please see attached image
![example](https://user-images.githubusercontent.com/68653276/92565766-7d946d80-f27b-11ea-92d4-37f07e473446.png)

Segment: 
- It represents row of elements in EntryView
- It contains JavaFx nodes
- Segments can be vertically aligned to one of three positions: TOP, CENTER, BOTTOM
- All children of segments are alligned to left, right or stay in the center.
- Segment has property "visibilityWeight" which defines priority of this segment and how long will stay on screen during zooming out - when new height of entry won't be enough big for all segments, firstly we hide segments with the lowest "visibilityWeight"

Please let us know: what do you think about this functionality? Would you be interested in merging our future implementation of this feature in CalendarFX? Let us know if you have any suggestions or questions to this idea.

Best regards,
PSI Polska - ASM Team

**Comment by dlemmermann** [comment]
The "attached" image is missing :-)

**Comment by dlemmermann** [comment]
Will I merge it? Yes, if the feature is useful for others and the quality of the pull request is good.

**Comment by PSI-Polska-ASM** [comment]
@dlemmermann Sorry, added image :)
