### ISSUE TITLE
Gap between Time and Entries in DetailedDayView

### ISSUE THREAD

**Issue by raoufOnGithub** [dlemmermann/CalendarFX#115]
Hello everyone !

I am using **DetailedDayView** in my program and I recently found out that there is a gap between Time and Entries when I specify a start and end time.
I specified here **start time at 08:00** and **end time at 15:00**, as you can see the entry starts at 10:30 but its aligned with 11:00.

![image](https://user-images.githubusercontent.com/58991057/97895730-7302cb80-1d34-11eb-9d4a-178289fe84b7.png)

Any solutions ?

**Comment by dlemmermann** [comment]
Looks like you ran into a bug here. Can you provide a standalone example, please? Once submitted I will try to find the time to fix it (or anybody else who feels up to ti).

**Comment by raoufOnGithub** [comment]
Here's a simple example.
View start time: 08:00
View  end time: 15:00
Entry start time: 10:00
Entry end time: 11:00

```
@Override
    public void start(Stage primaryStage) {
        AnchorPane anchorPane = new AnchorPane();

        // Creating Calendar
        CalendarSource calendarSource = new CalendarSource("Source");
        Calendar calendar = new Calendar("Calendar");

        // Creating Entry
        Entry entry = new Entry<>("New Entry");
        entry.setInterval(LocalDate.now());
        entry.changeStartTime(LocalTime.of(10, 0));
        entry.changeEndTime(LocalTime.of(11, 0));

        // Adding Entry to Calendar
        calendar.addEntry(entry);
        calendarSource.getCalendars().add(calendar);

        // Creating DetailedDayView
        DetailedDayView detailedDayView = new DetailedDayView();
        detailedDayView.setShowAllDayView(false);

        // Initialize DetailedDayView
        detailedDayView.setEarlyLateHoursStrategy(DayViewBase.EarlyLateHoursStrategy.HIDE);
        detailedDayView.setStartTime(LocalTime.of(8, 0));
        detailedDayView.setEndTime(LocalTime.of(15, 0));

        // Add Calendar to DetailedDayView
        detailedDayView.getCalendarSources().add(calendarSource);

        detailedDayView.setPrefWidth(1000);
        detailedDayView.setPrefHeight(600);

        anchorPane.getChildren().add(detailedDayView);

        Scene scene = new Scene(anchorPane);
        primaryStage.setScene(scene);
        primaryStage.show();
    }
```

**Comment by dlemmermann** [comment]
A first analysis shows that the view works fine with a more "normal" time range like 6am to 22pm. When I use a narrow range like yours it breaks. It might also be related to the current time being outside your specified range. I will do some more tests to get to the bottom of this issue.

**Comment by dlemmermann** [comment]
Fixed.
