### ISSUE TITLE
Deactivte ContextMenu in AgendaView

### ISSUE THREAD

**Issue by raoufOnGithub** [dlemmermann/CalendarFX#116]
I am trying to deactivate ContextMenu (Look Ahead/Back Period) in AgendaView but redefining `setContextMenuCallback(null)` or `setEntryContextMenuCallback(null)` does not work.

![image](https://user-images.githubusercontent.com/58991057/98956446-54ed5600-2500-11eb-84fb-96660e4bad92.png)

Any help ?

**Comment by dlemmermann** [comment]
Yes, this is implemented as a standard context menu directly on the AgendaView control. So you have to call AgendaView.setContextMenu(null).
