### ISSUE TITLE
Source tray is shown in full width when activated programmatically

### ISSUE THREAD

**Issue by nagychris** [dlemmermann/CalendarFX#117]
Maybe i am doing something wrong, but when i set the source tray (tray with all calendar sources on the left) of the `CalendarView` via `calendarView.setShowSourceTray(true)` before the start of my Application, the source tray is initially shown in full width of the window/scene, see screenshot:

![image](https://user-images.githubusercontent.com/65423853/106026281-eb75f000-60c9-11eb-8fac-95a4917215b0.png)

**Comment by dlemmermann** [comment]
It behaves differently for me. For me it does not become full size but definitely bigger than when shown later.

**Comment by dlemmermann** [comment]
Try calling it like this:  Platform.runLater(() -> calendarView.setShowSourceTray(true));

**Comment by dlemmermann** [comment]
The problem is that the tray is implemented via the MasterDetailPane of ControlsFX and that pane uses an animation. That animation is not working well in quite a few situations. Unfortunately I can not blame anyone for it because I also wrote the MasterDetailPane :-)

**Comment by nagychris** [comment]
Thanks for the tip, it solved the problem 👍🏻
