### ISSUE TITLE
Use of CalendarFX

### ISSUE THREAD

**Issue by oliszymanski** [dlemmermann/CalendarFX#118]
can I customize my own calendar window by creating a separate javaFX object?

**Comment by dlemmermann** [comment]
This question is way too generic :-)

But to answer in general terms: tons of stuff in CalendarFX can be customized. Customization can happen on different levels. Via the API, via CSS, via composing different calendar controls together to a new control.

**Comment by oliszymanski** [comment]
k, sry for troubling you... Im just new to github haha
