### ISSUE TITLE
Publish artefacts to Maven central.

### ISSUE THREAD

**Issue by dlemmermann** [dlemmermann/CalendarFX#12]
Now that release 8.4.1 is finished we need to publish the artefacts to a central repository. If anyone knows how to do this, please let me know.

**Comment by wimdeblauwe** [comment]
http://maven.apache.org/guides/mini/guide-central-repository-upload.html has some information.

**Comment by mkarneim** [comment]
Sonatype has a simple workflow for publishing artefacts to maven central: http://central.sonatype.org/pages/ossrh-guide.html. 
It is really easy. [Here](https://github.com/mkarneim/pojobuilder/blob/master/HOW%20TO%20RELEASE.md) is what I do, when I publish a new release of PojoBuilder.

**Comment by dlemmermann** [comment]
Done, CalendarFX is now on jcenter and maven central.
