### ISSUE TITLE
EventHandler

### ISSUE THREAD

**Issue by ruizhengxu** [dlemmermann/CalendarFX#129]
Hello, I would like to add an EventHandler to my both calendars to check if there is a new Entry added or changed.
What I'm trying to do with my application is to save all entries into a file (JSON for example), and then add these entries when the user quits the application and relaunch it later. So I need to know while the user using the application if there are new entries or entries are changed or deleted.

After viewing the documentation, I did several tries by creating a handler and try to output entries into the console but nothing, and I have no idea how to do. By the way, some lines of code in the documentation are not working in my project like this : `birthdays.addEventHandler(CalendarEvent.ANY, evt -> handleEvent(evt));`

It will be very helpful if you have answer to my problem.

What I tried : 

            CalendarView calendarView = new CalendarView();

            Calendar birthdays = new Calendar("Birthdays");
            Calendar holidays = new Calendar("Holidays");

            //EventHandler<CalendarEvent> handler = evt -> foo(evt);
            
            // Not Working
            // The method addEventHandler(EventHandler<CalendarEvent>) in the type Calendar is
            // not applicable for the arguments (EventType<CalendarEvent>, (<no type> evt) -> {}) 
            //birthdays.addEventHandler(CalendarEvent.ANY, evt -> handleEvent(evt));
            
            
            EventHandler<CalendarEvent> handler = new EventHandler<CalendarEvent>() {
				@Override
				public void handle(CalendarEvent event) {
					// TODO Auto-generated method stub
					System.out.println("CHANGE");
					System.out.println(event.getEntry());
				}
            };
            
            calendarView.addEventHandler(CalendarEvent.ENTRY_CHANGED, handler);
            calendarView.addEventFilter(CalendarEvent.ANY, handler);
            birthdays.addEventHandler(handler);

**Comment by dlemmermann** [comment]
You definitely need to add the handler to the calendar, not the view. I just verified that this should work fine. I added an event handler inside the CalendarApp class to the calendar "dirk" like this:`dirk.addEventHandler(evt -> System.out.println(evt));`

**Comment by ruizhengxu** [comment]
Problem solved, I just need to remove `CalendarEvent.ANY` in the method, thank you very much for the answer!
