### ISSUE TITLE
Error from ical4j when opening EntryDetailView in CalendarFXApp

### ISSUE THREAD

**Issue by jprie** [dlemmermann/CalendarFX#146]
Hey,

I am currently trying out calendarFX for the first time in a teaching setting.

I am using temurin-17 and saw the behaviour on Windows and  Mac OS.

Built the GitHub repo as adviced: mvn install, mvn javafx:run

The CalendarFXApp opens fine and looks perfect, but when I create a new Entry (in DayView) and DoubleClick it for opening the EntryDetailView I experience a lag, then the following Error[1] is logged (using org.slf4j-simple) and then the EntryDetailView shows up normal.

Since I'm new to the project, I'm not quite sure, where to start...

Thanks, Regards
Johannes

[1]
[calendarfx_error_ical4j_entrydetailview.txt](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/files/8444469/calendarfx_error_ical4j_entrydetailview.txt)

**Comment by dlemmermann** [comment]
I just tried it and it works fine for me.
Please make sure to use the maven wrapper in the project "mvnw".
First "./mvnw clean install" in the top level directory.
Then "../mvnw javafx:run" inside the CalendarFXApp module.

**Comment by dlemmermann** [comment]
Temurin 17 should work fine.

**Comment by jprie** [comment]
using the wrapper did not change the outcome. still the same error. I added org.slf4j:slf4j-simple  as dependency in pom.xml of CalendarFXApp to see the message.

**Comment by jprie** [comment]
Thanks for the swift reply!

I digged deeper and found out that only certain ZoneIDs trigger the error. All of them starting with ical4j~..., so for the moment, not calling Zone.of and not inserting them into the zoneIds "fixes the issue". 

At ical4j website I read that these "ical4j~..." are a special encoding for fixing an incompatibility.

So I guess I better ask the developer of iCal4j for further infos and this issue can be closed.

Thanks for your help.
