### ISSUE TITLE
Memory leaks in entry editors

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#149]
There are some memory leaks caused by the adding of non-weak listeners to calendar entry properties. 

At least the following views are affected:
EntryDetailsView (entry.intervalProperty().addListener and entry.recurrenceRuleProperty().addListener)
EntryPopOverContentPane (entry.calendarProperty().addListener)
EntryHeaderView (entry.calendarProperty().addListener)

**Comment by dlemmermann** [comment]
Fixed.
