### ISSUE TITLE
NullPointerException when changing a recurring entry to non-recurring

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#150]
Steps to reproduce:

1. Create a new entry
2. Edit the entry and change to recurring (e.g. Every Day)
3. Edit the entry and change back to non-recurring (None)

Also, the end result displayed by the WeekView is strange, see screenshot (happens even if I eliminate the NPE problem).

[stacktrace.txt](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/files/8785309/stacktrace.txt)
![non-recurring-screenshot](https://user-images.githubusercontent.com/106371135/170667737-36a23f39-f962-41c2-904a-5743b973f227.PNG)

**Comment by dlemmermann** [comment]
Fixed as part of another fix after IntelliJ told me that the "rule" String could be null.
