### ISSUE TITLE
Old context menu displayed beneath new one

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#151]
When triggering the context menu for an entry the second and subsequent trigger will result in two context menus being displayed on top of each other. When an item in the top-most (new) context menu is selected and the menu is hidden the old context menu is revealed beneath.

Steps to reproduce:
1. Create a new entry
2. Right-click the new entry and select an item (no extra context menu beneath)
3. Right-click the same new entry and select an item (old context menu revealed)

**Comment by dlemmermann** [comment]
Fixed as part of #155. This is all about having the right owner set on something that can auto-hide.
