### ISSUE TITLE
EntryDetailsView modifies the calendar entry when loading new time interval

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#152]
When the time interval of an entry is updated the EntryDetailsView will load the new time interval into the user interface. This load causes the time fields to change (in the order that they are updated) which in turn causes it to update the entry.

E.g. an entry with time interval 12:00 to 13:00 is opened in the EntryDetailsView. Changing the start time to 12:10 by editing the minute field will update the entry with this new start time while maintaining the duration of the entry, thus the end time will also be updated to 13:10. This new interval is loaded into the user interface causing the end time field to change from 13:00 to 13:10, which in turn will cause it to try to update the entry time interval.

Suggestion: disable updating of calendar entry due to field changes while loading new time interval.

**Comment by dlemmermann** [comment]
Done, flag added.
