### ISSUE TITLE
TimeField updates the value property while a new value is being loaded

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#153]
TimeField consists of two text fields; hour and minute. When the value property containing the time is invalidated the value is loaded into the text fields. When either text field is invalidated (the field value might still be the same) the updateValue method is called which in turn sets the value property if the time changed. When loading a new value the hour field is always updated first. This triggers an invalidation event at which time the minute field still has the old value, which in turn means that the property value will be updated.

E.g. create an entry with start time 12:00 and end time 13:00. Edit the start time to 12:10. This causes the following updates to the entry time interval:

start time=12:10, end time=13:10 (triggered by initial edit)
start time=12:10, end time=13:00 (triggered by loading the hour part of the end time)
start time=12:10, end time=13:10 (triggered by loading the minute part of the end time)

Suggestion: prevent calling of updateValue while loading the new time value.

**Comment by dlemmermann** [comment]
Done as proposed. See TimeFieldSkin.
