### ISSUE TITLE
Handling of calendar entries with different zone IDs

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#154]
It is possible to specify a zone ID for each calendar entry. However, the zone ID does not affect the display of the entries; two entries with identical local times (and local dates) but different zone IDs are displayed in the same exact location in the various calendar views which seems strange. Also; moving an entry by dragging always resets the time zone to the system default.

Question: what is the intended use of the entry zone ID? I'd like to be able to specify (and retain) a zone ID different from my local one for each entry but still have them displayed according to my local (or some other specified) zone.

**Comment by dlemmermann** [comment]
This feature has now been implemented and will be available in the next release.
