### ISSUE TITLE
The entry editor popover opened via the Information context menu item is opened at the wrong location

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#155]
Double-clicking an entry to open the entry details produces a popover next to the clicked entry.
Invoking the "Information" context menu item for the same entry produces a popover that is placed relative to the encapsulating DateControl.

**Comment by dlemmermann** [comment]
The wrong owner was passed to the method that shows the popover. Fixing this issue finally makes the popover behaviour consistent all over the framework.
