### ISSUE TITLE
Tests fails when building 8.4.1

### ISSUE THREAD

**Issue by teymourlouie** [dlemmermann/CalendarFX#17]
I downloaded 8.4.1 release and run `mvn package`

some tests failed with the following message:

`
Failed tests: 
  TimeZoneConverterTest.testConvertMonteCarlo:84->assertOffsetsEqualForDate:183 offset=1511948151291 in Pacific/Tongatapu expected:<50400000> but was:<46800000>
`

**Comment by dlemmermann** [comment]
Interesting. Currently I have no idea what is going on there. Could you do some more investigation?

**Comment by teymourlouie** [comment]
I tried to figure it out. The difference between expected value and actual one is ONE HOUR. It could be the daylight saving.
