### ISSUE TITLE
Memory leak when setting type in ResourcesView

### ISSUE THREAD

**Issue by andersb** [dlemmermann/CalendarFX#183]
Switching between type in a resource view will lead to out of memory.

**Comment by dlemmermann** [comment]
OK, I would suggest that you continue with plan B for now as I do not know how much time this will take. So create new instances whenever the view changes.

**Comment by andersb** [comment]
Can I create 3 different ones, add all resources to all of them and then switch between them? or would it be better to create new instances when view changes?

**Comment by dlemmermann** [comment]
Fixed.
