### ISSUE TITLE
setWeekViewFactory is ignored when switching to Type.DATE_OVER_RESOURCES

### ISSUE THREAD

**Issue by andersb** [dlemmermann/CalendarFX#185]
When using a custom week view factory, it will be ignored when type is DATE_OVER_RESOURCES but to work for RESOURCES_OVER_DATE

**Comment by dlemmermann** [comment]
This is correct, because the view DATE_OVER_RESOURCES does not use WeekView instances. It uses DayView instances, hence it uses the day view factory on ResourcesView. :-)
