### ISSUE TITLE
Editing recurring events results in incorrect visualization

### ISSUE THREAD

**Issue by JBalthasar** [dlemmermann/CalendarFX#191]
Visualization of recurring events works as expected as long as the events are not updated after the initial load into a DateControl. However, if a recurring event is updated and the date visualised by the DateControl contains other events the result of updating (the time) of a recurring event is that the first event (or multiple events when editing a full day recurring event) of the viewed date is added to the DateControl. Forcing a full refresh of the view corrects the situation.

The cause of this seems to be in how DayViewSkin and AllDayViewSkin handle updates of recurring events; updating a recurring event causes the skin to query the calendar for entries for the visualized date but it does not limit the processing of the result to the events associated by the updated event. Instead either the first event (DayViewSkin) or multiple events (AllDayViewSkin) of the date are added.

**Comment by JBalthasar** [comment]
Seems this might have been fixed a few days ago. I will try to update to the latest version.

**Comment by dlemmermann** [comment]
Yeah, there were some issues left in that area. Hope it works for you now.

**Comment by JBalthasar** [comment]
The latest release (and what is on trunk) has improved the behaviour for non-full day recurring events. Marking a recurring event as a full day event still results in strange behaviour. Also, editing a recurring full day event does not work properly; editing stuff like the title or trying to change the start date of the recurring full day event does not produce the expected result. Double-clicking the all-day row to add a new full day event causes a ghost event to be displayed at 12:00 the same day.

**Comment by JBalthasar** [comment]
Release 11.12.2 still has some issues wrt recurring events; 
1. Adding multiple full day recurring events for the same day can result in the wrong event being inserted in the all day view section.
- Steps to reproduce: create two daily recurring events in the week view, then change first the earlier one to full day and then the other. This results in the earlier event being displayed twice in the all day view.
2.  Editing the title of a full day event does not update the associated recurring events visible in the same view.

**Comment by dlemmermann** [comment]
Please verify with release 11.12.3 if these issues have been resolved.

**Comment by JBalthasar** [comment]
Works as expected in 11.12.3, thanks!
