### ISSUE TITLE
Maven repository failing

### ISSUE THREAD

**Issue by dirkey** [dlemmermann/CalendarFX#20]
I get the following error while building with gradle/maven:

   > Could not resolve com.calendarfx:view:8.4.1.
      > Could not parse POM http://jcenter.bintray.com/com/calendarfx/view/8.4.1/view-8.4.1.pom
         > Could not find com.calendarfx:calendar:8.4.1.

The error is a little bit misleading. You will notice in stacktrace and debug, that gradle won't find the parent pom http://jcenter.bintray.com/com/calendarfx/calendar/8.4.1/calendar-8.4.1.pom.

**Comment by dlemmermann** [comment]
Fixed.
