### ISSUE TITLE
Calendar is not visible

### ISSUE THREAD

**Issue by arias9306** [dlemmermann/CalendarFX#22]
When unchecking the calendar in the SourceView section and change the period in the day or week view and return again to the inicial view, the calendar is not visible anymore, that behavior is not present in the month view

For more details you can check the video [here](https://youtu.be/f3zdhybC9-o)

**Comment by arias9306** [comment]
Hi @dlemmermann,

This issue was solved in the pull request [#33](https://github.com/dlemmermann/CalendarFX/pull/33) on commit [5fc7361](https://github.com/dlemmermann/CalendarFX/pull/33/commits/5fc7361b2d2baf96b7fe68ca36651f069b9ccd13), You can see [here](https://github.com/dlemmermann/CalendarFX/files/2383373/calendar_visibility_ok.zip) the current behavior.

**Comment by dlemmermann** [comment]
Excellent job. Thank you!
