### ISSUE TITLE
Example for MyCustomEntryDialog

### ISSUE THREAD

**Issue by Ezak91** [dlemmermann/CalendarFX#23]
Hey,

can you give a short example implementation for the MyCustomEntryDialog

calendarView.setEntryDetailsCallback(param -> new MyCustomEntryDialog());

Thank you

**Comment by dlemmermann** [comment]
I don't think I have time for that :-) Basically you can pop up any kind of UI when the user double clicks on an entry. The callback defines a boolean return value. Currently this is not being used by the framework at all. You might want to take a look at the Dialog API of JavaFX.
