### ISSUE TITLE
Drag and drop functionality

### ISSUE THREAD

**Issue by WaLinke** [dlemmermann/CalendarFX#28]
Do you know if it's possible to drag and drop tags on the calendar and trigger an event to add this tag's datas to the calendar ?

**Comment by dlemmermann** [comment]
Oops, I never saw this issue come in. Sorry for not giving an answer. But yes, of course you can register drag and drop handlers and response to dropped "tags". Such handlers can be registered in various places and I think you need to investigate where it makes the most sense for your application.
