### ISSUE TITLE
Memory-Leak in DateControl/PopOver

### ISSUE THREAD

**Issue by FlorianKirmaier** [dlemmermann/CalendarFX#29]
The class [DateControl](https://github.com/dlemmermann/CalendarFX/blob/master/CalendarFXView/src/main/java/com/calendarfx/view/DateControl.java) has a static reference to the last PopOver.
```
private static PopOver entryPopOver;
```
This reference stays open, even if the Calendar is no longer used.

I noticed it, in the demo-server for [jpro.one](https://www.jpro.one), the last [CalendarApp](https://demos.jpro.one/calendar.html) always stays in the heap.

Removing `static` from the variable should fix the issue, but I'm not sure, whether this has any unwanted side-effects.

**Comment by dlemmermann** [comment]
I removed them. No idea why it was done like this. Creating new popover instances whenever needed works very well and they also auto-hide properly. Maybe this was something that needed more explicit coding in older versions of JavaFX.

**Comment by FlorianKirmaier** [comment]
Great, it's only fixed with JavaFX11, correct?

**Comment by dlemmermann** [comment]
Correct.
