### ISSUE TITLE
Disable drag and drop Entry

### ISSUE THREAD

**Issue by GabrielZulian** [dlemmermann/CalendarFX#30]
Is it possible to easily disable the drag and drop for the entry? I only want change the day or interval of an entry programmatically, not in the UI.

**Comment by dlemmermann** [comment]
Yes you can, please take a look at DateControl.setEntryEditPolicy().

Dirk

**Comment by GabrielZulian** [comment]
Got it, thank you!

**Comment by e-magon** [comment]
Hey, could you please help me? @GabrielZulian 
I'm trying to disable the drag and drop feature too, I've checked the setEntryEditPolicy method but I can't understand how I should make the Callback<EntryEditParameter, Boolean> policy object that specifies it has to disable the drag.

Thank you

**Comment by dlemmermann** [comment]
You simply implement the callback. The parameter gets created by the framework and then sent to the callback. You simply need to return "false".

**Comment by e-magon** [comment]
Ok thanks, I finally figured it out.
I just call setEntryEditPolicy of the main "window" of the app (in this case a CalendarView object) and as the parameter an anonymous function that simply returns false.

Thank you again for your fast response
