### ISSUE TITLE
JavaDocs Errors

### ISSUE THREAD

**Issue by omniprof** [dlemmermann/CalendarFX#31]
When performing a complete clean and build on CalendarFX with NetBeans 8.2 I see numerous errors related to JavaDocs that you can see in JavaDocsErrors01.txt

Even more confusing is what happens if I choose to clean and build only CalendarFXView. Now the JavaDocs errors are different and you can see them in JavaDocsErrors02.txt

Java Version is 1.8.0_172
Clean new install of NetBeans
Local Maven repository is deleted before clean and build.

[JavaDocsErrors01.txt](https://github.com/dlemmermann/CalendarFX/files/2163859/JavaDocsErrors01.txt)
[JavaDocsErrors02.txt](https://github.com/dlemmermann/CalendarFX/files/2163864/JavaDocsErrors02.txt)

**Comment by dlemmermann** [comment]
The first file shows also the warnings related to the "recurrence" module, which you are not building in the second pass / second file. Hence the differences. The "recurrence" module was developed by folks at Google and I simply added the new support for the new java.time API. I did not feel like writing javadocs for all of that. Most of the errors in the "view" module are only "warnings", so my desire to fix them right now is pretty small. :-)

**Comment by omniprof** [comment]
Thank you for the explanation. I plan to use a Maven for my student’s projects but will use the source code to help explain how it all works. I also noted on Twitter that Eclipse Photon couldn’t handle the project and that I got angry when IntelliJ asked where my git.exe is. Unfortunately it degraded into a back and forth between Lukas and Geertjan. I think it’s back to cat pics on Twitter for me for a while.

Ken
________________________________
