### ISSUE TITLE
Day view multiple selection not working

### ISSUE THREAD

**Issue by arias9306** [dlemmermann/CalendarFX#39]
Hi @dlemmermann,

As you can see in attached [video](https://github.com/dlemmermann/CalendarFX/files/2383312/multiple_selection_day_view_not_working.zip), the multiple selection is not working correctly just in day view.

Note: Current issue was solved is Pull Request [#37](https://github.com/dlemmermann/CalendarFX/pull/37) on commits [697a8de](https://github.com/dlemmermann/CalendarFX/pull/37/commits/697a8dee1555518090a4ed2334734bca3852d03e) and [872f377](https://github.com/dlemmermann/CalendarFX/pull/37/commits/872f3774a04a9888c098aa1091bd93ef3e67d281)

**Comment by dlemmermann** [comment]
The attached video is missing.

**Comment by arias9306** [comment]
Yes, I'm sorry, I've attached it

**Comment by dlemmermann** [comment]
ok, thank you! So I can close this now, correct?
