### ISSUE TITLE
Data Save

### ISSUE THREAD

**Issue by KhalilAz** [dlemmermann/CalendarFX#40]
Hello ! CalendarFX is a great Framework ! i just have a problem with storing Data in local i tried iCal4j but no luck ! can anyone expailn the process for me ! Thanks !!

**Comment by dlemmermann** [comment]
There is no standard process for persisting the calendar data. You need to take the calendar model and implement a persistence solution that works for you. If you do find one that might be interesting for others, then please feel free to provide a pull request.
