### ISSUE TITLE
11.5.0 Unable to change event behavior 

### ISSUE THREAD

**Issue by j0nm1** [dlemmermann/CalendarFX#46]
I'm using CalendarFX 11.5.0 and want to restrict the user to only see the YearPage of the example. So I'm doing:

```
CalendarView calendarView = new CalendarView();
        calendarView.showYearPage();
        calendarView.setShowPageSwitcher(false);
        calendarView.setShowSearchField(false);
        calendarView.setShowSearchResultsTray(false);
        calendarView.setShowAddCalendarButton(false);
        calendarView.setShowPrintButton(false);
        calendarView.setShowDeveloperConsole(false);
```

The problem is that when I'm double-clicking a day, it switches the view. To change that behavior as well, I thought I simply have to provide a custom callback for the setEntryDetailsCallback function but this doesn't work.

`calendarView.setEntryDetailsCallback(param -> {
            System.out.println("Test");
            return true;
        });`

But I'm not even getting the "Test" printed. Am I missing something?

**Comment by j0nm1** [comment]
small update: I found out that the event triggers correctly on every page but not on the year page. Really strange.

**Comment by dlemmermann** [comment]
The callback's purpose is to bring up another UI when the user double clicks on an entry, e.g. a dialog or a popover, that allows the user to edit the entry. However, the switching between views is done by different code. When you double click a date in the year page / year view then a so-callled RequestEvent will be fired. This event "requests" the date and the CalendarView makes the DayView show up. If you want to see the events being created you can launch your application with -Dcalendarfx.developer=true. When this property is set you can bring up the "developer console" via SHORTCUT-D (CMD-D on Mac, CTRL-D on Windows). A drawer will show up at the bottom.

<img width="1709" alt="Screen Shot 2019-04-05 at 09 33 41" src="https://user-images.githubusercontent.com/9534301/55611605-49fc0c80-5786-11e9-9528-5b85c706fd6d.png">

Ideally you take full control of your UI by putting your calendar together yourself and simply use the YearPage and leave out anything else.

**Comment by dlemmermann** [comment]
CalendarView basically represents a full-fledged calendar solution. If you want just a piece of it then you need to put it together yourself.

**Comment by j0nm1** [comment]
Thank you!
That solved my problem, I'm using the YearView from now on and it works great.
