### ISSUE TITLE
Using CalendarFx 11.5.0 with openJFx 12 facing problem of Module not found

### ISSUE THREAD

**Issue by eagleCoders** [dlemmermann/CalendarFX#47]
I added controlsfx in my module-info.java like 

module base.education.ui {
	requires common.education.ui;
	requires javafx.controls;
	requires javafx.media;
	requires org.kordamp.ikonli.javafx;
	requires java.sql;
	requires org.fxyz3d.core;
	requires javafx.swing;
	requires com.calendarfx.view;
	requires com.calendarfx.recurrence;
	requires gson;
	opens baseImages;	
	opens base.education.ui to javafx.graphics;
	exports base.education.ui;
}

but when using the CalendarView in my module I am facing the following problem

Error occurred during initialization of boot layer
java.lang.module.FindException: Module controlsfx not found, required by com.calendarfx.view

Regards

**Comment by dlemmermann** [comment]
The PRs have been merged. Please try again and let me know if this issue can be closed.

**Comment by dlemmermann** [comment]
Actually I feel confident that this resolves this issue. Closing it.

**Comment by kr5ture** [comment]
@dlemmermann Looks like package available through both `mvnrepository` and `bintray` somehow still has dependency on `controlsfx` in version `9.0.1-SNAPSHOT`:
```
\--- com.calendarfx:view:11.5.0
     +--- org.openjfx:javafx-controls:11-ea+25
     |    \--- org.openjfx:javafx-graphics:11-ea+25
     |         \--- org.openjfx:javafx-base:11-ea+25
     +--- org.openjfx:javafx-fxml:11-ea+25
     |    \--- org.openjfx:javafx-controls:11-ea+25 (*)
     +--- com.calendarfx:recurrence:11.5.0
     |    \--- joda-time:joda-time:2.9.1
     +--- org.controlsfx:controlsfx:9.0.1-SNAPSHOT FAILED <--------------------------
     +--- de.jensd:fontawesomefx-commons:9.1.2
     \--- de.jensd:fontawesomefx-fontawesome:4.7.0-9.1.2
          \--- de.jensd:fontawesomefx-commons:9.1.2
```

Also in `module-info.java`
```
module com.calendarfx.view {

    requires controlsfx;
    requires javafx.controls;
    requires javafx.fxml;
    // (...)
}
```

Packages:
* https://mvnrepository.com/artifact/com.calendarfx/view/11.5.0
* https://jcenter.bintray.com/com/calendarfx/view/11.5.0/view-11.5.0.pom

**Comment by eagleCoders** [comment]
Yes, I am afraid it is. I checked out from GitHub and fixed the bugs
manually in my local workspace and it is working fine now.

**Comment by kr5ture** [comment]
I have used `jitpack.io` as a workaround. There are plans to [release new version](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/issues/41) with fixes soon.
