### ISSUE TITLE
Merge updates from master into master-11

### ISSUE THREAD

**Issue by saarmbruster** [dlemmermann/CalendarFX#59]
I recently submitted some pull requests (#55, #56, #58) which were merged into the master branch. Is it possible to also merge those into the master-11 branch?

The [changelog](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/blob/master-11/CHANGELOG.md) of the 11.8.0 release states that the pull requests were included but the actual code is not.

It would really help me out if you could create a new release that actually contains the code.

Thanks

**Comment by dlemmermann** [comment]
Interesting. The changelog gets automatically generated and it seems to list all changes from all branches. That needs fixing.

**Comment by dlemmermann** [comment]
So why did you submit the changes to master and not master-11?

**Comment by saarmbruster** [comment]
I thought the changes may be also interesting for the v8 release series and that the two branches would be synced. I can open a new pull request for the master-11 branch if that helps.

**Comment by dlemmermann** [comment]
Nope, all good. I cherry picked them.

**Comment by dlemmermann** [comment]
I have released version 11.8.1 with your commits. It might already be on jcenter and should appear on maven central within the next couple of hours.
