### ISSUE TITLE
Missing icons when packaging in uber jar

### ISSUE THREAD

**Issue by saarmbruster** [dlemmermann/CalendarFX#62]
I have faced a similar issue as in #57 but this was closed before I could comment on it.

In my scenario I build an uber jar which contains my own code as well as CalendarFX in the same jar file. The jar was built using the Maven Assembly Plugin. When executed, the icons where missing and I got a bunch of UnsupportedOperationExceptions.

I traced down the issue and I found out that the plugin does not merge the files inside `META-INF/services`. So the file `org.kordamp.ikonli.IkonHandler` does not contain the name of the FontAwesome handler.

I fixed the problem by using the Maven Shade Plugin instead which is able to merge the service files. The following code builds a uber jar with the correct service handler:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>3.2.1</version>
    <executions>
        <execution>
            <goals>
                <goal>shade</goal>
            </goals>
            <configuration>
                <transformers>
                    <transformer
                    implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer">
                    </transformer>
                </transformers>
            </configuration>
        </execution>
    </executions>
</plugin>
```

I don't think this can be fixed in CalendarFX itself but it might be worth mentioning in the README. It is also worth mentioning that this only affects uber jars.

**Comment by dlemmermann** [comment]
Thanks for the info.

**Comment by valentingc** [comment]
This (see #57) is also a problem when using gradle.
When using the regular "jar" task to build a fat jar (which is what I need, sadly), the Ikonli icons are broken:
```
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'fa-XYZ'
	at org.kordamp.ikonli.javafx.IkonResolver.resolveIkonHandler(IkonResolver.java:62)
```

I solved this problem by using the Gradle Shadow plugin. For those of you who also encounter this problem, add the following contents to your build.gradle file:

```
plugins {
    // Apply the java plugin to add support for Java
    id 'java'
    id 'application'
    id "com.github.johnrengelman.shadow" version "5.2.0"
    // some left out here
}
application {
    mainClassName = 'com.xxx.Main'
}

// some left out here
shadowJar {
    archiveFileName = 'shadowJar.jar'
    mergeServiceFiles() // this one is important
    manifest {
        attributes(
                'Main-Class': "com.xxx.Main"
        )
    }
}
```

The main reason why this happens is that there are multiple files called `org.kordamp.ikonli.IkonHandler` in the Folder `META-INF\services`.
One can also manually merge the contents of the file to:

```
org.kordamp.ikonli.fontawesome.FontAwesomeIkonHandler
org.kordamp.ikonli.IkonliIkonResolver
```

Also, make sure that your main class is a regular Java class and NOT the one extending Application (else you'll have some struggles with the JavaFX module loading).

**Comment by dlemmermann** [comment]
Out of scope for CalendarFX.
