### ISSUE TITLE
Custom entry style not considered

### ISSUE THREAD

**Issue by saarmbruster** [dlemmermann/CalendarFX#64]
The `Entry`class provides a method `getStyleClass()` that offers, according to the docs, the ability to add a custom style for an entry. However, the custom style is not applied consequently.

I use the custom styles to apply different background colors to the entries. I noticed the following issues:

1. After moving an entry in DayView the style is removed
2. AllDayView does not apply style when fullday state is set to `true` after applying the custom style
3. MonthView ignores the custom style completely
4. MonthSheetView ignores the custom style completely

I already found a way to fix 1, 2 and 3. I can open a PR to fix these issues.

For 4 I don't see any easy solution since it does not use the entry style classes but instead refers to the color of the related calendar.

**Comment by dlemmermann** [comment]
Please create a separate ticket if item 4. is still important to you.
