### ISSUE TITLE
Only hide Early/Late Hours context menu item

### ISSUE THREAD

**Issue by saarmbruster** [dlemmermann/CalendarFX#71]
When start time is set to `LocalTime.MIN` and end time is set to `LocalTime.MAX` the context menu of `DayView` only shows the "Add new Event" entry. I  think only the "Early/Late Hours" entry should be hidden in this case. "Grid" and "Show Hours" should still be shown.

**Comment by dlemmermann** [comment]
PR was closed due to merging conflicts but change was done by me in a direct commit to master-11.
