### ISSUE TITLE
images don't show up

### ISSUE THREAD

**Issue by jameskwi** [dlemmermann/CalendarFX#73]
**_I have used the calendar in my app, and I have multi screens, the screen for calendar works fine, but the other screens have some images, once I test it, it shows me this error_** 
" 

> Exception in Application start method
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
> 	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
> Caused by: java.lang.RuntimeException: Exception in Application start method
> 	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$159(LauncherImpl.java:182)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.IllegalArgumentException: Invalid URL: Invalid URL or resource not found
> 	at javafx.scene.image.Image.validateUrl(Image.java:1118)
> 	at javafx.scene.image.Image.<init>(Image.java:620)
> 	at com.hospital.view.ImageDemo.start(ImageDemo.java:25)
> 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$166(LauncherImpl.java:863)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$179(PlatformImpl.java:326)
> 	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
> 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
> 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at com.sun.glass.ui.win.WinApplication.lambda$null$152(WinApplication.java:177)
> 	... 1 more
> Caused by: java.lang.IllegalArgumentException: Invalid URL or resource not found
> 	at javafx.scene.image.Image.validateUrl(Image.java:1110)
> 	... 11 more
> Exception running application com.hospital.view.ImageDemo

"

**my class is simple as the image below**

![Screenshot_2](https://user-images.githubusercontent.com/20887946/72548425-b6707400-389f-11ea-9d4a-86dc5a1dbb77.png)

**I have test the original calendar alone, and it works fine, see below:** 

![Screenshot_3](https://user-images.githubusercontent.com/20887946/72549054-0b60ba00-38a1-11ea-9942-21fe2d716485.png)

**but after I tried to add class for image inside the original project, same problem shows again,**

![Screenshot_4](https://user-images.githubusercontent.com/20887946/72549104-26332e80-38a1-11ea-8575-9218c6856e0f.png)

**please need help.
Thanks**

**Comment by dlemmermann** [comment]
The error message says it quite clearly: " Invalid URL: Invalid URL or resource not found". Closing this ticket.
