### ISSUE TITLE
Adding a major number of entries at once to calendars results in application freeze

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#74]
When I add 250 entries to 10 calendars (each calendar has around 25 entries) while initializing the calendar view, everything works fine and very fast. But when I add the same number of entries when the view is already opened, it lasts several (~20) seconds (in order to add entries to a calendar I’m using the com.calendarfx.model.Calendar#addEntries(java.util.Collection<com.calendarfx.model.Entry<?>>) method).
As far as I can see, while initialization there is only one event handler assigned to a calendar. But after the view has been initialized, there are already ~7 event handlers registered. The most time-consuming handler is located in AgendaViewSkin: impl.com.calendarfx.view.AgendaViewSkin#updateList(com.calendarfx.model.CalendarEvent, java.lang.String). There is also a suggestive comment 😃 :
> // TODO: this can be optimized more to only update when really needed

As far as I can see, the whole list of entries is being updated for each updated entry - which seems unnecessary. I'm talking about the 11.8.3 version btw.

PS. Are there any limitations regarding the number of entries added to a calendar? I heard that CalendarFX is not intended to show that big number of entries as e.g. FlexGanttFx is. Does the limitation refer just to the number of visible entries or entries that are assigned to a calendar in total?

![calendarfx_freezes](https://user-images.githubusercontent.com/34687474/74930620-56a94380-53de-11ea-94bd-78a8daf33d89.png)

**Comment by dlemmermann** [comment]
On DateControl you will find a property called "suspendUpdates". Please give that a try. It is bound between all nested date controls. So setting it on the parent view should be sufficient.

  
```
    /**
     * A property that will suspend all updates to the view based on model changes. This feature
     * comes in handy when performing large batch updates with many adds and / or removes of calendar
     * entries. When this property is set to true the view will not add / remove / update any entry
     * views. Once it is set back to false a single refresh will be executed.
     *
     * @return true if updates are suspended
     */
    public final BooleanProperty suspendUpdatesProperty() {
        return suspendUpdates;
    }
```

**Comment by adrianjaroszewicz** [comment]
Works great, thank you!
