### ISSUE TITLE
Width of entries in resource header is not equal

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#75]
The width of columns adjust to their content and does not correspond to the rest of the view (see attachment).
This is how I create a header for a given resource:

    private Node getResourceHeader( Resource resource )
    {
        Label label1 = new Label( resource.getId() );
        Label label2 = new Label( resource.getName() );
        label1.setStyle( "-fx-font-weight: bold;" );

        label1.setAlignment( Pos.CENTER );
        label2.setAlignment( Pos.CENTER );

        VBox box = new VBox( 0, label1, label2 );
        box.setPadding( new Insets( 3 ) );
        box.setFillWidth( false );
        box.setAlignment( Pos.CENTER );
        return box;
    }
![calendarfx_resource_header](https://user-images.githubusercontent.com/34687474/75889228-e1516000-5e2c-11ea-8612-c0911c414d6e.png)

**Comment by dlemmermann** [comment]
You mean the headers and the day view columns are not aligned any more?

**Comment by adrianjaroszewicz** [comment]
Yes, exactly.

**Comment by dlemmermann** [comment]
I pushed a first possible fix. Please let me know if this solves your issue.

**Comment by dlemmermann** [comment]
Please close this ticket if your requirement is supported now.

**Comment by adrianjaroszewicz** [comment]
Works great, thank you!
