### ISSUE TITLE
Current time marker indicator is being repeated for each resource (when using ResourceCalendarView)

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#76]
Please see the attachment. Is it possible to show the circle only once, at the left side of the line?
![calendarfx_current_time](https://user-images.githubusercontent.com/34687474/75890675-fcbd6a80-5e2e-11ea-9208-0c988aa77a59.png)

**Comment by dlemmermann** [comment]
Yes, this should not be a problem. I will look into it.

**Comment by dlemmermann** [comment]
I just pushed a change that will allow you to control the visibility of the red line and the red dot individually. Take a look at the ResourceCalendarApp where you will find this code fragment:

```java
            DayView dayView = resourceCalendarView.getDayView(resource);
            dayView.getCalendarSources().setAll(source);
            dayView.setEnableCurrentTimeMarker(true);
            dayView.setEnableCurrentTimeCircle(i == 0);
```

**Comment by dlemmermann** [comment]
Please close this ticket if your requirement is supported now.

**Comment by adrianjaroszewicz** [comment]
Works great, thank you!
