### ISSUE TITLE
CalendarFXGoogle: Blank window

### ISSUE THREAD

**Issue by mkroening** [dlemmermann/CalendarFX#78]
When starting `com.calendarfx.google.GoogleCalendarApp` from `master-11`, I only see a blank window and no Google Login web page.

Is this the intended behavior?

**Comment by dlemmermann** [comment]
No it is not. And I also do not see this. I see this sequence of screens.
<img width="1512" alt="Screenshot 2020-05-08 at 11 17 16" src="https://user-images.githubusercontent.com/9534301/81391608-ac5bd500-911d-11ea-8bd8-2fec1a7e0868.png">
<img width="1512" alt="Screenshot 2020-05-08 at 11 17 37" src="https://user-images.githubusercontent.com/9534301/81391612-ae259880-911d-11ea-839e-9c276c5d29c5.png">
<img width="1512" alt="Screenshot 2020-05-08 at 11 17 44" src="https://user-images.githubusercontent.com/9534301/81391618-afef5c00-911d-11ea-84fb-0649371cf203.png">
<img width="1512" alt="Screenshot 2020-05-08 at 11 17 49" src="https://user-images.githubusercontent.com/9534301/81391623-b1b91f80-911d-11ea-864a-dd4b727947b1.png">
<img width="1512" alt="Screenshot 2020-05-08 at 11 18 01" src="https://user-images.githubusercontent.com/9534301/81391631-b382e300-911d-11ea-9b3b-043a83462799.png">

**Comment by mkroening** [comment]
Ah, yes. Working on my machine now as well. Thanks!
