### ISSUE TITLE
Font erros

### ISSUE THREAD

**Issue by phamvanthanh** [dlemmermann/CalendarFX#83]
Hi,
I did my first try and got this problem. 
How to fix it?
<img width="1259" alt="Screen Shot 2020-03-13 at 23 07 42" src="https://user-images.githubusercontent.com/24784468/76639267-67ce1600-6580-11ea-800e-83bbc60a8483.png">

**Comment by dlemmermann** [comment]
That does not look like a CalendarFX-specific issue. Have you tried running other JavaFX applications? Or Java applications in general?

**Comment by phamvanthanh** [comment]
I am coding Javafx, never seen this error. 
I have no ideas about this font problem too. 
BTW, is ready for use? I mean I am going to use it to for works.

**Comment by phamvanthanh** [comment]
Hi.
It now works perfectly. No Ideas why
