### ISSUE TITLE
Day view ALIGN_LEFT stategy doesn't work with intersecting entries

### ISSUE THREAD

**Issue by ftrela** [dlemmermann/CalendarFX#85]
Inside the entry view factory the Entry1 entry view has set specific pref width and alignment strategy to `ALIGN_LEFT`:

```
entryView.setPrefWidth(20);
entryView.setAlignmentStrategy(EntryViewBase.AlignmentStrategy.ALIGN_LEFT);
```

The Entry2 entry has default alignment strategy `EntryViewBase.AlignmentStrategy.FILL`

When the Entry1 and Entry2 intersect and the Entry1 start time is later than the Entry2 start time, then the Entry1 is no longer on the left side of the day view. Please look at the image below:
![CalendarFX_align_left_strategy](https://user-images.githubusercontent.com/20297211/79429924-774dde00-7fc8-11ea-8a2f-54eb1e256a7b.png)

I would expect that after setting the `EntryViewBase.AlignmentStrategy.ALIGN_LEFT`, the entry view always shows up on the left side of the day view. Is it possible?

**Comment by dlemmermann** [comment]
Unfortunately not. The algorithm that deals with overlapping entries does not take the alignment property into consideration.

**Comment by dlemmermann** [comment]
Could it be that all you need is a way to "disable" the resolution of overlapping entries and have more manual control? Same for issue #86 ?

**Comment by ftrela** [comment]
I think it should be ok. As I understand, you want to provide an additional API for this manual control. Could you roughly say, what will this API look like? And what about drag-and-drop visualization, will it follow the rules defined by this new API?

**Comment by dlemmermann** [comment]
On DayViewBase I would have a method like "setEnableOverlappingEntries(true)". And yes, while dragging an entry that setting would also be applied.

**Comment by dlemmermann** [comment]
I have added the property autoLayout to DayViewBase, which means it is also available for the ResourceCalendarView. There the value is set to false, so CalendarFX will no longer try to place entries with overlapping time intervals in separate columns. Please let me know if this solves this issue.

**Comment by ftrela** [comment]
As I noticed while commenting the other issue (#86), the `autoLayout` property is no longer there - and there were also some changes made in the algorithm that deals with overlapping entries. Could you consider also placing the entry on the left, the center, or the middle **of the entry view** and not a given column in which the entry has been placed (when the `com.calendarfx.view.EntryViewBase#setAlignmentStrategy` has been used)? It looks like a good thing for the CalendarFX anyways since from the point of view of usability it would look better (I can imagine that someone wants to freeze a narrow calendar entry at a certain position of the day view for a specific kind of activity so that he would remember it better) - and also from the point of view of the API, `entryView.setAlignmentStrategy(AlignmentStrategy.ALIGN_LEFT)` suggests that the entry will be located on the left side of the view.
That would be a big deal for us since in other scenario we would have to re-write the already existing overlapping algorithm ourselves. What do you think?

**Comment by ftrela** [comment]
As I wrote in the #86 issue, I came up with another solution for this problem, so I'm closing this issue.
