### ISSUE TITLE
Listener to a mouse click on a TimeScaleView

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#87]
I would like to add a marker to a resource calendar view right after the user clicks with the left mouse button on the time scale:
![calendarfx_time_scale](https://user-images.githubusercontent.com/34687474/79571254-2ec31d00-80bb-11ea-99c8-859a2d0cdd7b.png)
Because the area selected by a red rectangle it is a `TimeScaleView` right?

Is it possible to retrieve the `TimeScaleView` control from a `ResourceCalendarView`? I can see that it is available in the `ResourceCalendarViewSkin` but it is not visible to the outside world - so it is hard to attach a listener to it. But maybe there is another way of getting to it that I'm not aware of.

**Comment by dlemmermann** [comment]
you can perform a lookup to get it, but only after the skin has been set on it.

Something like this would do it:

view.skinProperty().addListener(it -> {
	TimeScaleView view = (TimeScaleView) view.lookup(“TimeScaleView”); // maybe lookup(“.time-scale-view”)
});

Dirk

**Comment by adrianjaroszewicz** [comment]
Oh yes, I forgot about the lookup. Great, that was exactly what I was looking for, thank you!

**Comment by raoufOnGithub** [comment]
Hello there,
I am using an AgendaView, I have set the calendar source and the calendar and I would like now to add a right mouse button listener on the selected entry on the AgendaView and I need some help to do it if you guys have any idea how to proceed.
