### ISSUE TITLE
Reusability of DayEntryViewSkin

### ISSUE THREAD

**Issue by imario42** [dlemmermann/CalendarFX#9]
Dirk, in DayEntryViewSkin, are you fine if I change the methods private modifier to protected so we are able to easily reuse and enhance it outside of the CalendarFX?

**Comment by dlemmermann** [comment]
Yes, fine with me. But then also please add javadocs.

**Comment by imario42** [comment]
Committed. I've also introduced a new method setupUpdateListeners.
