### ISSUE TITLE
Deactivate right click event on DetailedDayView (or any other view)

### ISSUE THREAD

**Issue by raoufOnGithub** [dlemmermann/CalendarFX#90]
Hello everyone !

Im using CalendarFX with JDK 14 and OpenJFX 14 on IntelliJ and Scene Builder 11.0 for the GUI. All the dependencies im using are up-to-date.

I want to use a DetailedDayView but only for consulting: the user **can't add a new entry** (_double-click_) nor **show the context menu** (_right-click_).

I have found a solution for the double click event using this code :
`@FXML
    private DetailedDayView dayView;`
`EventHandler<MouseEvent> handler = MouseEvent::consume;`
`dayView.addEventFilter(MouseEvent.ANY, handler);`

But the _right click_ event still works I am still trying to figure it out.

Here is my FXML code:
`<VBox fx:id="vbox">
<children>
<DetailedDayView fx:id="dayView" earlyLateHoursStrategy="HIDE" prefHeight="720.0" prefWidth="1000.0" />
</children>
</VBox>`

Thank you for your help!

**Comment by dlemmermann** [comment]
Use `setContextMenuCallback(null)` to disable the context menu. Call `setEntryFactory(param -> null)` to disable the creation of new entries.

**Comment by raoufOnGithub** [comment]
Working perfectly! thank you.
