### ISSUE TITLE
How to remove or change mouse events of a view

### ISSUE THREAD

**Issue by raoufOnGithub** [dlemmermann/CalendarFX#91]
Hello everyone !

Im trying to remove the mouse events on a DetailledDayView and replace them with my own events but I couldnt do it after 2 days of trying!
If someone has a solution I would be very grateful. Thanks.

P.S.: Im using JDK 11 with OpenJFX 14 under IntelliJ

**Comment by dlemmermann** [comment]
CalendarFX uses higher level concepts that "hide" mouse events, e.g. a context menu callback that can be registered with any DateControl. What exactly is it that you do not want to happen and what is it that you want to happen instead?

**Comment by dlemmermann** [comment]
I guess I can close this now after answering in the other ticket.
