### ISSUE TITLE
Order of entries when the OverlapResolutionStrategy.VISUAL_BOUNDS has been chosen

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#93]
Is it possible to control the order of entries when the `OverlapResolutionStrategy.VISUAL_BOUNDS` has been chosen?
![calendarfx_entries_sorting](https://user-images.githubusercontent.com/34687474/81934347-1decc500-95ef-11ea-912c-309f48083118.gif)

As it is being shown in the gif, I have connected two resource calendar views (they are bound using the scroll time property + entry from the view on the left has a corresponding entry in the view on the right). The view on the left uses the `TIME_BOUNDS` strategy and the view on the right uses the `VISUAL_BOUNDS` strategy.

In order to present the dependency of entries in a more precise way, I have bound the selection in both views. To make it even more precise, I would like to sort entries located in the view on the right in the same order as corresponding entries from the view in the left (in this view there is more than one resource). The logic I would like to go with would probably look like 

```
Comparator.comparing( entry::dateFrom ).thenComparing( correspondingEntry::resourceTitle ).thenComparing( correspondingEntry::title )
```

(fortunately the `correspindingEntry::resourceTitle` and `correspindingEntry::title` is a business information that I have access to in the scope of the entry from the view on the right)

In the `com.calendarfx.model.Entry#compareTo` I have found a logic that is being used for sorting entries - but the method is final so there is no way for me to introduce an additional condition.

But even if I was able to do so, there is one more obstacle: `impl.com.calendarfx.view.util.VisualBoundsResolver#resolve`. Here I can see a custom comparator that is based on the location of the entry. I'm not quite sure what is the purpose of such custom sorter - is it used for the sake of the performance? And probably my main question: Is it possible to override it somehow or run an additional sorting after placements have been determined? Or maybe there is another way for solving my issue that I haven't thought of?

**Comment by dlemmermann** [comment]
I think this is asking for some kind of support on the Resolver class. I will look into it.

**Comment by dlemmermann** [comment]
Sorry for the delay. I added two new static methods on TimeBoundsResolver and VisualBoundsResolver. You can now set an "additional" comparator that kicks in if two entries are identical (same start time or same start-y coordinate).

**Comment by dlemmermann** [comment]
Can I close this?

**Comment by adrianjaroszewicz** [comment]
Now I am sorry for the delay, I had some urgent issues to solve and couldn't check that yet :/ I will do my best to do it tomorrow.

**Comment by adrianjaroszewicz** [comment]
Ok, I've checked that and after introducing the additional comparator I have some problems with the overlapping. After a quick investigation I've noticed that there is a typo in `impl.com.calendarfx.view.util.VisualBoundsResolver#resolve`.
There is:
`final Range range2 = getRange(o1, dayView, contentWidth);`
Shouldn't it be 
`final Range range2 = getRange(o2, dayView, contentWidth);`?

**Comment by dlemmermann** [comment]
Fixed and pushed. Please try again.

**Comment by adrianjaroszewicz** [comment]
Works great, thank you! :)
