### ISSUE TITLE
The minimal height of the entry depends on the titleLabel height

### ISSUE THREAD

**Issue by adrianjaroszewicz** [dlemmermann/CalendarFX#99]
Hello Dirk,
we have noticed that the height of the entry depends on the height of the `titleLabel`. In our case the title is not always represented just by a single line but a couple of them - and when the entry is, lets say, 30 minutes long, zooming in and out doesn't affect its height. In that case it can be quite confusing when the entry actually ends. I have found the code responsible for that (`impl.com.calendarfx.view.DayEntryViewSkin#computeMinHeight`):
```
    @Override
    protected double computeMinHeight(double width, double topInset,
                                      double rightInset, double bottomInset, double leftInset) {
        if (titleLabel != null) {
            // For this pref height calculation we do not consider the available
            // width because
            // we only want to show a single line of text anyways.
            return titleLabel.prefHeight(-1) + topInset + bottomInset;
        }

        return super.computeMinHeight(width, topInset, rightInset, bottomInset, leftInset);
    }
```
In order not to depend on the `titleLabel` I have overridden this method and replaced its implementation with the implementation from `javafx.scene.control.SkinBase#computeMinHeight`. It works well but copying the code from other libraries is not the cleanest solution and can be hard to maintain. Would you consider adding a property that indicates if the height of the entry should be dependent on the title height or not? Or any other way to control this behaviour. It's not that important issue but I thought it's a nice-to-have option in the framework as well. To be honest I do not have any information about the status of your agreement with PSI - but I'm reporting this issue anyway, hoping that everything has been agreed :) If not, it can wait.

**Comment by dlemmermann** [comment]
I added a property called DayEntryView.minHeightEqualToTitleHeight() as requested by the ticket.
